[package]
name = "marker_utils"
version = "0.1.0"
edition = "2021"
license = "MIT OR Apache-2.0"
keywords = ["marker", "linting"]
categories = ["development-tools"]
repository = "https://github.com/rust-marker/marker"
description = "Marker's standard library for creating lints"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
marker_api = { path = "../marker_api" }
