[workspace]
members = [
    "cargo-marker",
    "marker_adapter",
    "marker_api",
    "marker_rustc_driver",
    "marker_utils",
    "marker_lints",
    "marker_uitest",
    "marker_uilints",
]
resolver = "2"

[workspace.metadata.marker.lints]
marker_lints = { path = "./marker_lints" }
