[workspace]
members = [
    "cargo-marker",
    "marker_adapter",
    "marker_api",
    "marker_driver_rustc",
    # This is needed for rust-analyzer, uitests and other tools
    "marker_lints",
]

[workspace.metadata.marker.lints]
marker_lints = { path = "marker_lints" }
