[workspace]
members = [
    "cargo-marker",
    "marker_adapter",
    "marker_api",
    "marker_rustc_driver",
    # This is needed for rust-analyzer, uitests and other tools
    "marker_lints",
]
resolver = "2"

[workspace.metadata.marker.lints]
marker_lints = { path = "marker_lints" }
