[workspace]
members = [
    "cargo-marker",
    "marker_adapter",
    "marker_api",
    "marker_rustc_driver",
    "marker_utils",
    "marker_lints",
    "marker_uitest",
    # A dummy crate, to have a manifest for uitests
    "ui_test_manifest",
]
resolver = "2"

[workspace.metadata.marker.lints]
marker_uitest = { path = "marker_uitest" }
