[package]
name = "marker_lints"
version = "0.1.0"
edition = "2021"
license = "MIT OR Apache-2.0"
keywords = ["marker", "lint"]
repository = "https://github.com/rust-marker/marker"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
crate-type = ["cdylib"]

[dependencies]
marker_api = { path = "../marker_api", version = "0.1.0" }

[dev-dependencies]
marker_uitest = { path = "../marker_uitest", features = ["dev-build"] }

[[test]]
name = "uitest"
harness = false
