[package]
name = "marker_uilint"
version = "0.1.0"
edition = "2021"
license = "MIT OR Apache-2.0"
publish = false

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
crate-type = ["cdylib"]

[dependencies]
marker_api = { path = "../marker_api" }

[dev-dependencies]
ui_test = "0.11.5"
tempfile = "3.5.0"
