[package]
name = "marker_adapter"
version = "0.1.0"
edition = "2021"
license = "MIT OR Apache-2.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
marker_api = { path = "../marker_api" }
marker_utils = { path = "../marker_utils" }

libloading = "0.8.0"
cfg-if = "1.0.0"
