[package]
name = "cargo_marker"
version = "0.1.0"
edition = "2021"
license = "MIT OR Apache-2.0"

# Crate names in Rust are fun. I reserved `cargo_marker` as a crate name. However,
# Cargo requires it's subcommands to use a dash like `cargo-marker`. Unable to rename
# rename the create on crates.io we now have this hack... At least it works
[[bin]]
name = "cargo-marker"
path = "src/main.rs"

[dependencies]
clap = { version = "4.0.26", features = ["string"] }
serde = { version = "1.0", features = ["derive"] }
toml_edit = { version = "0.17.1", features = ["easy"] }
once_cell = "1.16.0"
cargo_fetch = "0.1.2"

[features]
default = []
# This enables developer features used to automatically build the local version
# assuming, that it's being executed at the root of the repo.
dev-build = []
