[package]
name = "cargo-marker"
version = "0.1.0"
edition = "2021"
license = "MIT OR Apache-2.0"

[dependencies]
clap = {version = "4.0.26", features = ["string"]}
once_cell = "1.16.0"

[features]
default = []
# This enables developer features used to automatically build the local version
# assuming, that it's being executed at the root of the repo.
dev-build = []
