[alias]
dogfood = "run --features dev-build --bin cargo-marker -- --forward-rust-flags"
uitest = "test --test uitest"
bless = "test --test uitest -- -- --bless"
uilints = "test -p marker_uilints --test uitest"

[profile.dev]
split-debuginfo = "unpacked"
