[package]
categories  = ["development-tools"]
description = "Marker's API, designed for stability and usability"
edition     = "2021"
keywords    = ["marker", "linting"]
license     = "MIT OR Apache-2.0"
name        = "marker_api"
repository  = "https://github.com/rust-marker/marker"
version     = "0.1.1"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
visibility = "0.0.1"

[features]
# Some items should only be used by the driver implementing the functionality,
# this feature enables the export of these items. Note that this interface is
# unstable. All usage of the driver api can change between releases.
driver-api = []
