[package]
name = "marker_uitest"
version = "0.1.1"
edition = "2021"
license = "MIT OR Apache-2.0"
keywords = ["marker", "linting"]
repository = "https://github.com/rust-marker/marker"
description = "A thin wrapper around the ui_test crate for Marker"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ui_test = "0.11.7"
tempfile = "3.6.0"
semver = "1.0"

[features]
default = []
# This feature indicates that `marker_utils` is used inside the marker repo. This will
# build and run the `cargo-marker` binary instead of invoking it via `cargo marker`.
dev-build = []
