name: Docs

on:
  push:
    paths:
      - '**.md'
      - './docs/**'
  pull_request:
    paths:
      - '**.md'
      - './docs/**'

jobs:
  # Build job
  mdbook:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: ./scripts/download/mdbook.sh
      - name: Build the book
        run: |
          PATH="$PATH:`pwd`"
          cd ./docs/book/
          mdbook build
          cd ../../
