# This file has to be kept in sync with `rust_bors.yml`
name: Rust

on:
  push:
    # Don't run tests, when only text files were modified
    paths-ignore:
    - 'COPYRIGHT'
    - 'LICENSE-*'
    - '**.md'
    - '**.txt'
    # Bors magic branches, these are covered by `rust_bors`
    branches-ignore:
    - '**.tmp'
    - 'staging'
    - 'trying'
    - 'master'
  pull_request:
    # Don't run tests, when only text files were modified
    paths-ignore:
    - 'COPYRIGHT'
    - 'LICENSE-*'
    - '**.md'
    - '**.txt'

env:
  RUST_BACKTRACE: 1
  CARGO_TERM_COLOR: always
  RUSTDOCFLAGS: "-Dwarnings"
  RUSTFLAGS: "-Dwarnings"

jobs:
  rust:
    runs-on: ubuntu-latest

    # Setup
    steps:
    - uses: actions/checkout@v3
    - uses: dtolnay/rust-toolchain@master
      with:
        toolchain: nightly-2023-07-13
        components: rustfmt, clippy

    - run: rustc -vV

    # Tests
    - run: cargo test
    - run: cargo clippy
    - run: cargo fmt --check
    - run: cargo doc --no-deps

  # This task ensures, required packages can be built with a stable toolchain
  # the only package requiring nightly should be `marker_rustc_driver` and
  # optionally `marker_adapter`
  rust-crates-build-stable:
    runs-on: ubuntu-latest

    # Setup
    steps:
    - uses: actions/checkout@v3
    - run: rm rust-toolchain
    - uses: dtolnay/rust-toolchain@master
      with:
        toolchain: stable

    - run: rustc -vV

    # Test
    - run: cargo build --package cargo_marker
    - run: cargo build --package marker_api
    - run: cargo build --package marker_utils
    - run: cargo build --package marker_uitest
    - run: cargo build --package marker_uilints

  # Check the formatting of TOML files in the repository
  toml:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: ./scripts/download/taplo.sh
      - run: ./taplo fmt --check

  # Check for typos in the repository based on a static dictionary
  typos:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: ./scripts/download/typos.sh
      - run: ./typos

  # Check for unused dependencies that uses simple regex search,
  # meaning it's ⚡️ blazingly ⚡️ fast
  rust-unused-dependencies:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: ./scripts/download/cargo-machete.sh
      - run: ./cargo-machete
